# streamlit_app.py
# -*- coding: utf-8 -*-
# xray-steps-parser v1.7 (Import-Safe Fields + Scenario Type + Call Test + Links)

"""
Streamlit – Xray Test Steps Parser (CSV → Flat Table)

v1.7 additions
- Keeps import-related Xray/Jira fields when present in Jira CSV All Fields export
- Adds Scenario Type as customfield_29221 export column
- Keeps Scenario Expected Result, Test Type, Test Environment, Test Sets, Test Plans, Pre-Conditions
- Keeps issue links such as Inward/Outward issue link columns
- Parses Xray Call Test steps from Manual Test Steps JSON via testCallBean
- Parses step attachment metadata from Manual Test Steps JSON
- Preserves duplicate Jira columns on export by removing pandas .1/.2 suffixes only at download time
"""

import json
import re
from typing import List, Dict, Any

import pandas as pd
import streamlit as st

# ---------------------------
# Helpers
# ---------------------------

def find_col(cols: List[str], needle: str) -> str:
    """Find the FIRST column whose name contains `needle` (case-insensitive)."""
    needle_low = needle.lower()
    for c in cols:
        if needle_low in c.lower():
            return c
    return ""


def find_col_any(cols: List[str], needles: List[str]) -> str:
    """Find first column matching any needle."""
    for n in needles:
        found = find_col(cols, n)
        if found:
            return found
    return ""


def get_strict_cols(cols: List[str], needle: str) -> List[str]:
    """
    Find strictly the duplicate columns generated by pandas for a specific field.
    E.g. needle="Labels" -> exactly "Labels", "Labels.1", "Labels.2"
    """
    needle_low = needle.lower()
    base_col = None
    for c in cols:
        if needle_low in c.lower():
            base_col = c
            break

    if not base_col:
        return []

    clean_base = re.sub(r"\.\d+$", "", base_col)
    escaped_base = re.escape(clean_base)

    pattern = re.compile(rf"^{escaped_base}(\.\d+)?$")
    return [c for c in cols if pattern.match(c)]


def get_prefixed_cols(cols: List[str], prefixes: List[str]) -> List[str]:
    """Return columns that start with any prefix; useful for issue link fields."""
    out = []
    for c in cols:
        c_low = c.lower()
        if any(c_low.startswith(p.lower()) for p in prefixes):
            out.append(c)
    return out


def _clean_text(x: Any) -> str:
    s = str(x) if x is not None else ""
    s = s.replace("\u00a0", " ")
    s = re.sub(r"\s+", " ", s, flags=re.UNICODE).strip()
    return s


def _join_non_empty(values: List[Any], sep: str = " | ") -> str:
    cleaned = []
    for v in values:
        if v is None:
            continue
        s = _clean_text(v)
        if s:
            cleaned.append(s)
    return sep.join(cleaned)


def _read_cell(row: pd.Series, col: str) -> str:
    if not col:
        return ""
    val = row.get(col, "")
    if pd.isna(val):
        return ""
    return val


def _read_cols(row: pd.Series, cols: List[str]) -> Dict[str, str]:
    data = {}
    for col in cols:
        val = row.get(col, "")
        data[col] = "" if pd.isna(val) else val
    return data


def _parse_json_array(cell: Any) -> List[Dict[str, Any]]:
    if not isinstance(cell, str) or not cell.strip():
        return []
    s = cell.strip().replace("\u00a0", " ")
    try:
        arr = json.loads(s)
    except Exception:
        try:
            arr = json.loads(s.replace("'", '"'))
        except Exception:
            return []
    return arr if isinstance(arr, list) else []


def _extract_step_attachments(item: Dict[str, Any]) -> Dict[str, str]:
    attachments = item.get("attachments", []) if isinstance(item, dict) else []
    if not isinstance(attachments, list):
        attachments = []
    filenames = []
    urls = []
    paths = []
    for att in attachments:
        if not isinstance(att, dict):
            continue
        filenames.append(att.get("fileName", ""))
        urls.append(att.get("fileURL", ""))
        paths.append(att.get("filePath", ""))
    return {
        "Step Attachments": _join_non_empty(filenames),
        "Step Attachment URLs": _join_non_empty(urls),
        "Step Attachment Paths": _join_non_empty(paths),
    }


def parse_manual_steps_cell(cell: Any) -> List[Dict[str, Any]]:
    """Parse Manual Test Steps. Supports normal steps and Xray Call Test steps."""
    arr = _parse_json_array(cell)
    out = []

    for item in arr:
        if not isinstance(item, dict):
            continue

        fields = item.get("fields", {}) if isinstance(item.get("fields", {}), dict) else {}
        call = item.get("testCallBean", {}) if isinstance(item.get("testCallBean", {}), dict) else {}
        attachments = _extract_step_attachments(item)

        if call:
            call_key = _clean_text(call.get("issueKey", ""))
            call_summary = _clean_text(call.get("issueSummary", ""))
            out.append({
                "Step #": item.get("index"),
                "Step Type": "Call Test",
                "Action": f"Call Test: {call_key} - {call_summary}".strip(" -"),
                "Data": "",
                "Expected Result": "",
                "Call Test Key": call_key,
                "Call Test Summary": call_summary,
                "Call Test Steps Number": call.get("stepsNumber", ""),
                **attachments,
            })
        else:
            out.append({
                "Step #": item.get("index"),
                "Step Type": "Manual Step",
                "Action": _clean_text(fields.get("Action", "")),
                "Data": _clean_text(fields.get("Data", "")),
                "Expected Result": _clean_text(fields.get("Expected Result", "")),
                "Call Test Key": "",
                "Call Test Summary": "",
                "Call Test Steps Number": "",
                **attachments,
            })

    return out


# Xray/Jira import-critical and preservation fields.
# The left side is output name; the right side contains possible CSV export column names.
OPTIONAL_IMPORT_FIELDS = {
    "Project key": ["Project key"],
    "Issue Type": ["Issue Type"],
    "Status": ["Status"],
    "Affects Version/s": ["Affects Version/s"],
    "Fix Version/s": ["Fix Version/s"],
    "Component/s": ["Component/s"],
    "Environment": ["Environment"],
    "customfield_29221": ["Custom field (Scenario Type)", "Scenario Type", "Scenario Tye", "customfield_29221"],
    "Scenario Expected Result": ["Custom field (Scenario Expected Result)", "Scenario Expected Result"],
    "Test Type": ["Custom field (Test Type)", "Test Type"],
    "Test Environment": ["Custom field (Test Environment)", "Test Environment"],
    "Test Repository Path": ["Custom field (Test Repository Path)", "Test Repository Path"],
    "Test Review": ["Custom field (Test Review)", "Test Review"],
    "Test Case Source": ["Custom field (Test Case Source)", "Test Case Source"],
    "Test Sets association with a Test": ["Custom field (Test Sets association with a Test)", "Test Sets association with a Test"],
    "Test Plans associated with a Test": ["Custom field (Test Plans associated with a Test)", "Test Plans associated with a Test"],
    "Pre-Condition Type": ["Custom field (Pre-Condition Type)", "Pre-Condition Type"],
    "Pre-Conditions association with a Test": ["Custom field (Pre-Conditions association with a Test)", "Pre-Conditions association with a Test"],
    "Generic Test Definition": ["Custom field (Generic Test Definition)", "Generic Test Definition"],
}


def detect_optional_fields(cols: List[str]) -> Dict[str, str]:
    detected = {}
    for out_name, candidates in OPTIONAL_IMPORT_FIELDS.items():
        detected[out_name] = find_col_any(cols, candidates)
    return detected


def build_flat(df: pd.DataFrame, col_map: Dict[str, Any]) -> pd.DataFrame:
    rows = []

    for _, r in df.iterrows():
        key = _read_cell(r, col_map["key"])
        prio = _read_cell(r, col_map["priority"])
        summ = _read_cell(r, col_map["sum"])
        desc = _read_cell(r, col_map["desc"])

        base_info = {
            "Issue key": key,
            "Priority": prio,
            "Summary": summ,
            "Description": desc,
        }

        # Optional import/preservation fields
        for out_name, src_col in col_map["optional"].items():
            base_info[out_name] = _read_cell(r, src_col)

        # Duplicate fields that Jira exports as repeated columns
        base_info.update(_read_cols(r, col_map["labels"]))
        base_info.update(_read_cols(r, col_map["test_sets_extra"]))
        base_info.update(_read_cols(r, col_map["precond_extra"]))
        base_info.update(_read_cols(r, col_map["link_cols"]))
        base_info.update(_read_cols(r, col_map["attachment_cols"]))

        steps_cell = _read_cell(r, col_map["steps"])
        steps = parse_manual_steps_cell(steps_cell)

        if not steps:
            rows.append({
                **base_info,
                "Step #": None,
                "Step Type": "",
                "Action": "",
                "Data": "",
                "Expected Result": "",
                "Call Test Key": "",
                "Call Test Summary": "",
                "Call Test Steps Number": "",
                "Step Attachments": "",
                "Step Attachment URLs": "",
                "Step Attachment Paths": "",
            })
        else:
            for s in steps:
                rows.append({**base_info, **s})

    flat = pd.DataFrame(rows)

    if flat.empty:
        return flat

    uniques = pd.unique(flat["Issue key"])
    case_map = {k: i + 1 for i, k in enumerate([u for u in uniques if pd.notna(u) and u != ""])}
    flat.insert(0, "Case #", flat["Issue key"].map(case_map))

    ordered_cols = ["Case #", "Issue key", "Project key", "Issue Type", "Status", "Priority", "Summary", "Description"]

    # Fields that are important for re-import / preservation
    ordered_cols.extend([
        "Affects Version/s",
        "Fix Version/s",
        "Component/s",
        "Environment",
        "customfield_29221",
        "Scenario Expected Result",
        "Test Type",
        "Test Environment",
        "Test Repository Path",
        "Test Review",
        "Test Case Source",
        "Test Sets association with a Test",
        "Test Plans associated with a Test",
        "Pre-Condition Type",
        "Pre-Conditions association with a Test",
        "Generic Test Definition",
    ])

    ordered_cols.extend(col_map["labels"])
    ordered_cols.extend(col_map["test_sets_extra"])
    ordered_cols.extend(col_map["precond_extra"])
    ordered_cols.extend(col_map["link_cols"])
    ordered_cols.extend(col_map["attachment_cols"])

    ordered_cols.extend([
        "Step #",
        "Step Type",
        "Action",
        "Data",
        "Expected Result",
        "Call Test Key",
        "Call Test Summary",
        "Call Test Steps Number",
        "Step Attachments",
        "Step Attachment URLs",
        "Step Attachment Paths",
    ])

    # Keep only existing cols and avoid duplicates in UI order
    seen = set()
    final_cols = []
    for c in ordered_cols:
        if c in flat.columns and c not in seen:
            final_cols.append(c)
            seen.add(c)

    # Add any remaining columns at the end, defensively
    for c in flat.columns:
        if c not in seen:
            final_cols.append(c)

    return flat[final_cols]


def collapse_repeats(df: pd.DataFrame, group_col: str, cols_to_blank: List[str]) -> pd.DataFrame:
    if df.empty or group_col not in df.columns:
        return df
    out = df.copy()
    safe_cols = [c for c in cols_to_blank if c in out.columns]
    for _, idx in out.groupby(group_col, sort=False).groups.items():
        if len(idx) > 1:
            out.loc[idx[1:], safe_cols] = ""
    return out


def df_to_csv_bom(df: pd.DataFrame, sep: str = ";") -> bytes:
    csv_str = df.to_csv(index=False, sep=sep, encoding="utf-8-sig")
    return csv_str.encode("utf-8-sig")


def make_jira_export_column_names(df: pd.DataFrame) -> pd.DataFrame:
    """
    Remove pandas duplicate suffixes (.1, .2) for repeated Jira columns.
    Also keep customfield_29221 as-is because this is the import field requested.
    """
    rename_map = {}
    for col in df.columns:
        if col == "customfield_29221":
            continue
        rename_map[col] = re.sub(r"\.\d+$", "", col)
    return df.rename(columns=rename_map)


# ---------------------------
# UI
# ---------------------------

st.set_page_config(page_title="Xray Steps Parser", page_icon="✅", layout="wide")
st.title("Xray Test Steps Parser")
st.caption("CSV All Fields → Ayrıştırılmış step tablosu + import için kritik Xray/Jira alanları")

uploaded = st.file_uploader("CSV yükle (Jira'dan Export → CSV All fields, ; ile ayrılmış)", type=["csv"])

if uploaded is None:
    st.info("Örnek: Jira 'Export → CSV (All fields)' çıktısı. Zorunlu sütun: 'Custom field (Manual Test Steps)'.")
    st.stop()

try:
    df_raw = pd.read_csv(uploaded, sep=";", dtype=str, low_memory=False)
except Exception:
    df_raw = pd.read_csv(uploaded, dtype=str, low_memory=False)

st.success(f"Yüklendi: {len(df_raw)} satır, {len(df_raw.columns)} sütun")

cols_list = df_raw.columns.tolist()

# Detect duplicate groups
labels_cols = get_strict_cols(cols_list, "Labels")
test_sets_cols = get_strict_cols(cols_list, "Custom field (Test Sets association with a Test)")
precond_cols = get_strict_cols(cols_list, "Custom field (Pre-Conditions association with a Test)")
attachment_cols = get_strict_cols(cols_list, "Attachment")
link_cols = get_prefixed_cols(cols_list, ["Inward issue link", "Outward issue link"])

# Since the first Test Sets / Precondition cols are already represented with clean output names,
# keep extra duplicate columns separately to avoid double output.
optional_detected = detect_optional_fields(cols_list)
first_test_sets = optional_detected.get("Test Sets association with a Test", "")
first_precond = optional_detected.get("Pre-Conditions association with a Test", "")

test_sets_extra = [c for c in test_sets_cols if c != first_test_sets]
precond_extra = [c for c in precond_cols if c != first_precond]

col_map = {
    "steps": find_col(cols_list, "Manual Test Steps"),
    "key": find_col(cols_list, "Issue key") or find_col(cols_list, "Key"),
    "priority": find_col(cols_list, "Priority"),
    "sum": find_col(cols_list, "Summary"),
    "desc": find_col(cols_list, "Description"),
    "labels": labels_cols,
    "test_sets_extra": test_sets_extra,
    "precond_extra": precond_extra,
    "link_cols": link_cols,
    "attachment_cols": attachment_cols,
    "optional": optional_detected,
}

missing = []
if not col_map["steps"]:
    missing.append("Manual Test Steps")
if not col_map["key"]:
    missing.append("Issue key")
if not col_map["sum"]:
    missing.append("Summary")

if missing:
    st.error("Zorunlu eksik sütun(lar): " + ", ".join(missing))
    st.stop()

with st.expander("Sütun eşlemesi / import için korunan alanlar"):
    st.write({
        "Manual Test Steps": col_map["steps"],
        "Issue key": col_map["key"],
        "Priority": col_map["priority"] or "(Bulunamadı)",
        "Summary": col_map["sum"],
        "Description": col_map["desc"] or "(Bulunamadı)",
        "Scenario Type → customfield_29221": col_map["optional"].get("customfield_29221") or "(Bulunamadı)",
        "Scenario Expected Result": col_map["optional"].get("Scenario Expected Result") or "(Bulunamadı)",
        "Test Type": col_map["optional"].get("Test Type") or "(Bulunamadı)",
        "Test Environment": col_map["optional"].get("Test Environment") or "(Bulunamadı)",
        "Test Repository Path": col_map["optional"].get("Test Repository Path") or "(Bulunamadı)",
        "Test Sets": [first_test_sets] + test_sets_extra if first_test_sets else test_sets_extra or "(Bulunamadı)",
        "Pre-Conditions": [first_precond] + precond_extra if first_precond else precond_extra or "(Bulunamadı)",
        "Labels Sütunları": col_map["labels"] if col_map["labels"] else "(Bulunamadı)",
        "Issue Link Sütunları": col_map["link_cols"] if col_map["link_cols"] else "(Bulunamadı)",
        "Attachment Sütunları": col_map["attachment_cols"] if col_map["attachment_cols"] else "(Bulunamadı)",
    })

collapse_opt = st.checkbox("Üst veri (Issue key, Summary, Priority, linkler vb.) sadece ilk satırda görünsün", value=True)

flat = build_flat(df_raw, col_map)

if collapse_opt and not flat.empty:
    step_cols = {
        "Step #", "Step Type", "Action", "Data", "Expected Result",
        "Call Test Key", "Call Test Summary", "Call Test Steps Number",
        "Step Attachments", "Step Attachment URLs", "Step Attachment Paths"
    }
    cols_to_blank = [c for c in flat.columns if c not in step_cols and c != "Case #"]
    flat = collapse_repeats(flat, group_col="Case #", cols_to_blank=cols_to_blank)

# Metrics
left, mid1, mid2, right = st.columns(4)
with left:
    st.metric("Toplam Case", df_raw[col_map["key"]].replace("", pd.NA).nunique())
with mid1:
    st.metric("Toplam Step", int(flat["Step #"].notna().sum()) if "Step #" in flat.columns else 0)
with mid2:
    st.metric("Call Test Adımı", int((flat["Step Type"] == "Call Test").sum()) if "Step Type" in flat.columns else 0)
with right:
    st.metric("Link Kolonu", len(col_map["link_cols"]))

st.subheader("Ayrıştırılmış Test Adımları")
st.dataframe(flat, use_container_width=True)

# Export column names
flat_export = make_jira_export_column_names(flat)

colA, colB = st.columns(2)
with colA:
    st.download_button(
        label="CSV indir (UTF-8 BOM, ; ile)",
        data=df_to_csv_bom(flat_export, sep=";"),
        file_name="manual_test_steps_import_safe_utf8.csv",
        mime="text/csv",
    )
with colB:
    st.download_button(
        label="CSV indir (UTF-8 BOM, , ile)",
        data=df_to_csv_bom(flat_export, sep=","),
        file_name="manual_test_steps_import_safe_utf8_comma.csv",
        mime="text/csv",
    )
